### ISSUE TITLE
Dancer-Plugin-Database-Core 0.15 not appearing on CPAN

### ISSUE THREAD

**Issue by joshrabinowitz** [bigpresh/Dancer-Plugin-Database#88]
See http://search.cpan.org/~ambs/

**Comment by bigpresh** [comment]
I released it, so it'd be under my CPAN ID (BIGPRESH) not AMBS.

I see it on CPAN: https://metacpan.org/release/Dancer-Plugin-Database-Core

**Comment by joshrabinowitz** [comment]
Hm, ok, that makes sense. 

I'm still not seeing Dancer::Plugin::SimpleCRUD 0.99 though, cpan still shows 0.98
http://search.cpan.org/~bigpresh/Dancer-Plugin-SimpleCRUD/

**Comment by joshrabinowitz** [comment]
thanks for the quick response

**Comment by bigpresh** [comment]
Hmm.  It appears I got interrupted between merging your changes, tweaking them slightly to add more docs, and releasing 0.99.  I'll get it out shortly.

**Comment by bigpresh** [comment]
9.99 is on its way to CPAN now, sorry about that!
